theme: jekyll-theme-midnight
# Conversion markdown: redcarpet 
highlighter: pygments 
redcarpet: extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

collections:
  stu:
    user: true
    image: true
    name: true
 
